const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function feedback(form,message){const panel=form.querySelector('[data-feedback]');panel.hidden=false;panel.textContent=message;panel.setAttribute('role','status')}
const menu=$('#menu'),search=$('#search-panel');
$('#menu-toggle').addEventListener('click',()=>{menu.hidden=!menu.hidden;$('#menu-toggle').setAttribute('aria-expanded',String(!menu.hidden));search.hidden=true;$('#search-toggle').setAttribute('aria-expanded','false')});
$('#search-toggle').addEventListener('click',()=>{search.hidden=!search.hidden;$('#search-toggle').setAttribute('aria-expanded',String(!search.hidden));menu.hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false');if(!search.hidden)$('#global-search').focus()});
const choices=[['Concorde — les collections','collections.html#concorde'],['Préparer votre parcours','audiences.html#planner'],['Agenda des expositions','agenda.html'],['Visiter en groupe','groups.html']];
$('#global-search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();const matches=q?choices.filter(([label])=>label.toLowerCase().includes(q)):choices;const items=[...matches,...choices.filter(([label])=>!matches.some(([match])=>match===label))];$('#suggestions').replaceChildren(...items.slice(0,4).map(([label,href])=>{const li=document.createElement('li'),a=document.createElement('a');a.href=href;a.textContent=label;li.append(a);return li}))});
const dialog=$('#info-dialog');
function info(title,message){$('#info-title').textContent=title;$('#info-body').textContent=message;dialog.showModal()}
$$('[data-info]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();const topic=el.dataset.info;let message='Cette rubrique fait partie du périmètre du futur site. Le contenu détaillé et son fonctionnement ne sont pas encore intégrés à cette démonstration.';if(topic==='Horaires & accès')message='Les horaires et exceptions affichés ici sont ceux du jeu de contenu de la maquette d’octobre 2026. Ils devront être administrés depuis le CMS et vérifiés avant la visite.';if(topic==='Concorde001')message='Concorde prototype001 F-WTSS · Hall Concorde. Envergure25,56m, vitesse maximale2200km/h. La fiche complète et les autres caractéristiques seront reprises du catalogue validé du musée.';if(topic==='Autre créneau')message='Dans le site livré, les créneaux disponibles seront proposés depuis See Tickets. L’état complet de cette maquette est illustratif.';if(topic==='Confidentialité')message='Cette démonstration ne transmet ni ne stocke les données saisies dans les formulaires. La politique du site livré détaillera les finalités, droits et durées de conservation.';info(topic,message)}));
$$('.dialog-close,.dialog-close-action').forEach(b=>b.addEventListener('click',()=>dialog.close()));
$('#language').addEventListener('click',()=>info('English — French fallback','This page is not available in English in this preview. You remain on the corresponding French page. The delivered website will provide French and British English content, with human-approved translations.'));
$$('.demo-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);if(form.dataset.demo==='group')feedback(form,'Votre demande est prête — démonstration uniquement. Aucune demande n’a été envoyée ou enregistrée; aucune réservation n’est confirmée.');if(form.dataset.demo==='newsletter')feedback(form,'Inscription illustrée uniquement. Votre adresse n’est ni transmise ni conservée.');if(form.dataset.demo==='planner'){const date=data.get('date');const interest=data.getAll('interests');const names=interest.includes('space')?['Hall de l’espace','Tarmac']:['Hall Concorde','Hall de l’espace','Tarmac'];const route=date==='2026-10-18'?names.filter(n=>n!=='Hall Concorde'):names;feedback(form,'Parcours de démonstration : '+route.join(' → ')+(date==='2026-10-18'?'. Le Hall Concorde est fermé à cette date.':'.')+' Les recommandations, conditions d’accès et durées seront validées avec le musée; aucun trajet précis n’est calculé dans cet aperçu.')}}));
$$('[data-map]').forEach(b=>b.addEventListener('click',()=>{$$('[data-map]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('[data-map-panel]').forEach(p=>p.hidden=p.dataset.mapPanel!==b.dataset.map)}));
function filterAgenda(){const form=$('#agenda-filters');if(!form)return;const data=new FormData(form);let count=0;$$('#programmes .programme').forEach(card=>{let visible=true;const date=data.get('date');if(date)visible=visible&&date>=card.dataset.start&&date<=card.dataset.end;for(const key of ['kind','cost','duration','availability'])if(data.get(key))visible=visible&&card.dataset[key]===data.get(key);if(data.get('audience'))visible=visible&&(card.dataset.audience==='all'||card.dataset.audience===data.get('audience'));card.hidden=!visible;if(visible)count++});$('#event-count').textContent=count+' événement'+(count===1?'':'s')+' présenté'+(count===1?'':'s')+' — sélection de démonstration';}
if($('#agenda-filters')){$('#agenda-filters').addEventListener('submit',e=>{e.preventDefault();filterAgenda()});$('#agenda-filters').addEventListener('reset',()=>requestAnimationFrame(filterAgenda))}
$$('[data-calendar]').forEach(b=>b.addEventListener('click',()=>{$$('[data-calendar]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#calendar-note').hidden=b.dataset.calendar!=='calendar'}));
if($('#collection-filters')){const form=$('#collection-filters');form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),query=String(data.get('query')||'').toLowerCase();let matches=!query||['concorde','prototype','001','f-wtss'].some(x=>x.includes(query));if(data.get('display')==='reserve')matches=false;const known={0:25.56,5:2200};let unknown=false;for(let i=0;i<8;i++){const min=data.get('tech'+i+'_min'),max=data.get('tech'+i+'_max');if(min||max){if(!(i in known)){unknown=true;continue}if(min&&known[i]<Number(min))matches=false;if(max&&known[i]>Number(max))matches=false}}$('#concorde').hidden=!matches;feedback(form,(matches?'1 objet présenté : Concorde001.':'Aucun objet de la sélection ne correspond.')+(unknown?' Certaines caractéristiques ne sont pas renseignées dans ce jeu de démonstration.':'')+' Le catalogue complet sera intégré après validation du musée.');});form.addEventListener('reset',()=>requestAnimationFrame(()=>{$('#concorde').hidden=false;form.querySelector('[data-feedback]').hidden=true}))}
